### ISSUE TITLE
clean urls: menu.html

### ISSUE THREAD

**Issue by S1M0NH** [vimalkvn/susty-pelican#1]
Hi. Great work on the theme. One issue that I'm struggling with is getting this:

`example.com/menu` instead of `example.com/menu.html`

same with tags and categories.

I've searched through the Pelican docs but no joy so far.

**Comment by vimalkvn** [comment]
Thanks for reporting this. I suspect it might be something to do with the configuration of the web server serving your pages. It works fine in my case. 

One possibility would be to use the following setting in `pelicanconf.py` instead:

`TEMPLATE_PAGES = {'menu.html': 'menu/index.html'}`

In fact, this is much cleaner. I will update the README. 

For categories and tags, you might want to have a look at the `CATEGORIES_SAVE_AS`, `TAGS_SAVE_AS` and related settings in the [documentation](https://docs.getpelican.com/en/stable/settings.html#url-settings).

**Comment by S1M0NH** [comment]
Brilliant. Sorted now!

Thanks again.
